name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: build ${{ matrix.name }}
    runs-on: ubuntu-22.04
    env:
      CGO_ENABLED: '0'
    strategy:
      matrix:
        include:
          - name: linux amd64
            env:
              GOOS: linux
              GOARCH: amd64
            file: zaia-linux-amd64
            compress: true
            strip: true

          - name: linux 386
            env:
              GOOS: linux
              GOARCH: 386
            file: zaia-linux-i386
            compress: true
            strip: true

          - name: darwin amd64
            env:
              GOOS: darwin
              GOARCH: amd64
            file: zaia-darwin-amd64
            compress: false
            strip: false

          - name: darwin arm64
            env:
              GOOS: darwin
              GOARCH: arm64
            file: zaia-darwin-arm64
            compress: false
            strip: false

          - name: windows amd64
            env:
              GOOS: windows
              GOARCH: amd64
            file: zaia-win-x64.exe
            compress: false
            strip: false

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
        id: go

      - name: get dependencies
        run: |
          export GOPATH=$HOME/go
          ./tools/install.sh
          echo "$PWD/bin" >> $GITHUB_PATH

      - name: build
        env: ${{ matrix.env }}
        run: >-
          go build
          -o builds/${{ matrix.file }}
          -ldflags "-s -w
          -X github.com/zeropsio/zaia/internal/commands.version=${{ github.ref_name }}
          -X github.com/zeropsio/zaia/internal/commands.commit=${{ github.sha }}
          -X 'github.com/zeropsio/zaia/internal/commands.built=$(date -u +%Y-%m-%dT%H:%M:%SZ)'"
          ./cmd/zaia/main.go

      - name: compress binary
        if: ${{ matrix.compress }}
        uses: svenstaro/upx-action@v2
        with:
          file: ./builds/${{ matrix.file }}
          strip: ${{ matrix.strip }}

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.file }}
          path: ./builds/${{ matrix.file }}

  release:
    name: create release
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./builds
          merge-multiple: true

      - name: create GitHub release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >-
          gh release create "${{ github.ref_name }}"
          ./builds/*
          --repo "${{ github.repository }}"
          --title "${{ github.ref_name }}"
          --generate-notes
